version: '3.8'
services:
  php:
    image: php:8.1-apache
    container_name: php-container
    ports:
      - "8080:80"
    volumes:
      - /app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: site_web
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  mysql-data:
